import InteractiveDesk from '@/components/InteractiveDesk';
import DonationExperiment from '@/components/DonationExperiment';
import Arrow from '@/components/Arrow';
import Navigation from '@/components/Navigation';
import { profile, projects, experiences, archive } from '@/content/site';
export default function Home(){return <><Navigation/><main id="main">
<section className="interactive-hero section-pad" id="home"><div className="hero-intro"><span className="eyebrow">UT AUSTIN / CLASS OF {profile.classYear}</span><h1>Sriram<br/>Kakumanu<span>.</span></h1><p className="intro-context">Product × Technology × Human Behavior</p><div className="intro-links"><a className="text-link" href="#work">Selected work <Arrow down/></a><a className="text-link" href="#explore">Explore <Arrow down/></a></div></div><InteractiveDesk/></section>
<section className="currently section-pad" id="currently"><h2 className="eyebrow">01 / CURRENTLY</h2><div><p>{profile.studies}</p></div><div className="currently-detail"><span className="eyebrow">THE UNIVERSITY OF TEXAS AT AUSTIN</span><p>Class of {profile.classYear}</p></div></section>
<section className="work section-pad" id="work"><div className="section-heading"><div><span className="eyebrow">02 / SELECTED WORK</span><h2>Selected work</h2></div></div><div className="project-list">{projects.map((p,i)=><article className={`project ${p.theme}`} key={p.id} id={p.id}><div className="project-visual">{i===0?<><span className="visual-meta">STUDYSENSE</span><div className="study-word">Aha<span>!</span></div><div className="orbit orbit-one"/><div className="orbit orbit-two"/></>:i===1?<DonationExperiment/>:<><span className="visual-meta">CREDIT CARD ADVISOR / PRODUCT EXPERIMENT</span><div className="sample-card"><div>Credit Card<br/>Advisor</div></div></>}</div><div className="project-copy"><span className="eyebrow">{p.category}</span><h3>{p.name}</h3><p>{p.description}</p>{p.href?<a className="text-link" href={p.href} target="_blank" rel="noopener noreferrer">Visit product <span aria-hidden="true"><Arrow/></span></a>:null}</div></article>)}</div></section>
<section className="experience section-pad" id="experience"><div className="section-heading"><div><span className="eyebrow">03 / EXPERIENCE</span><h2>Experience</h2></div></div><div className="experience-list">{experiences.map((e,i)=><article key={e.company}><span className="experience-index">0{i+1}</span><h3>{e.company}</h3><div><p>{e.role}</p>{e.context&&<span>{e.context}</span>}</div><span className="experience-arrow" aria-hidden="true"><Arrow/></span></article>)}</div></section>
<section className="transition section-pad"><h2>Beyond work<span><Arrow down/></span></h2></section>
<section className="explore section-pad" id="explore"><div className="section-heading"><div><span className="eyebrow">04 / EXPLORE</span><h2>Explore</h2></div></div><div className="archive-grid">{archive.map((a,i)=><article className={`archive-tile archive-${i}`} key={a.id}><div className="archive-placeholder"><span className="archive-number">0{i+1}</span><div className="archive-art" aria-hidden="true">{i===0?<Arrow/>:i===1?'✳':'◎'}</div><span className="archive-media-note">PHOTOGRAPHY TO COME</span></div><div className="archive-caption"><span className="eyebrow">{a.category}</span></div></article>)}</div></section>
<section className="contact section-pad" id="contact"><span className="eyebrow">05 / CONTACT</span><h2>Contact</h2><div className="contact-bottom"><a className="contact-link" href={profile.github} target="_blank" rel="noopener noreferrer">GitHub <span aria-hidden="true"><Arrow/></span></a></div></section>
</main><footer className="section-pad"><span>© {new Date().getFullYear()} {profile.name}</span><a href="#home">Back to top ↑</a></footer></>}
