import InteractiveDesk from '@/components/InteractiveDesk';
import DonationExperiment from '@/components/DonationExperiment';
import Arrow from '@/components/Arrow';
import Navigation from '@/components/Navigation';
import { profile, projects, experiences, archive } from '@/content/site';
export default function Home(){return <><Navigation/><main id="main">
<section className="interactive-hero section-pad" id="home"><div className="hero-intro"><span className="eyebrow">UT AUSTIN / CLASS OF {profile.classYear}</span><h1>Sriram<br/>Kakumanu<span>.</span></h1><p className="intro-statement">Products.<br/>People.<br/><em>Possibilities.</em></p><p className="intro-context">At the intersection of product, technology, and human behavior.</p><div className="intro-links"><a className="text-link" href="#work">Selected work <Arrow down/></a><a className="text-link" href="#explore">The other side <Arrow down/></a></div><span className="intro-footnote">A FEW THINGS FROM MY CORNER OF THE WORLD.</span></div><InteractiveDesk/></section>
<section className="currently section-pad" id="currently"><h2 className="eyebrow">01 / CURRENTLY</h2><div><span className="status-label"><i/> THE CHAPTER I’M IN</span><p>Studying business.<br/>Understanding people.<br/><span className="muted">Connecting the dots.</span></p></div><div className="currently-detail"><span className="eyebrow">THE UNIVERSITY OF TEXAS AT AUSTIN</span><p>{profile.studies}</p><span className="small-note">Building toward product, program, and technology roles.</span></div></section>
<section className="work section-pad" id="work"><div className="section-heading"><div><span className="eyebrow">02 / SELECTED WORK</span><h2>Ideas, put to work<span className="accent">.</span></h2></div><p>Different problems.<br/>The same curiosity.</p></div><div className="project-list">{projects.map((p,i)=><article className={`project ${p.theme}`} key={p.id} id={p.id}><div className="project-visual">{i===0?<><span className="visual-meta">STUDYSENSE / LEARNING, RECONSIDERED</span><div className="study-word">Aha<span>!</span></div><div className="study-line">A question is a good place to start.</div><div className="orbit orbit-one"/><div className="orbit orbit-two"/></>:i===1?<DonationExperiment/>:<><span className="visual-meta">CREDIT CARD ADVISOR / PRODUCT EXPERIMENT</span><div className="sample-card"><span>DECISIONS, BY DESIGN.</span><div>Consider<br/>your options.</div><span>RULES, NOT GUESSWORK ↗</span></div><span className="visual-bottom">AI-ASSISTED BUILD. HUMAN PRODUCT JUDGMENT.</span></>}</div><div className="project-copy"><span className="eyebrow">{p.category}</span><h3>{p.name}</h3><h4>{p.title}</h4><p>{p.description}</p>{p.href?<a className="text-link" href={p.href} target="_blank" rel="noopener noreferrer">Visit product <span aria-hidden="true"><Arrow/></span></a>:<span className="project-coming">Case study forthcoming <span aria-hidden="true"><Arrow/></span></span>}<span className="small-note project-note">{p.note}</span></div></article>)}</div></section>
<section className="experience section-pad" id="experience"><div className="section-heading"><div><span className="eyebrow">03 / EXPERIENCE</span><h2>Learning by doing<span className="accent">.</span></h2></div><p>Across products, teams,<br/>and different ways of thinking.</p></div><div className="experience-list">{experiences.map((e,i)=><article key={e.company}><span className="experience-index">0{i+1}</span><h3>{e.company}</h3><div><p>{e.role}</p>{e.context&&<span>{e.context}</span>}</div><span className="experience-arrow" aria-hidden="true"><Arrow/></span></article>)}</div><p className="small-note experience-note">Selected roles from the supplied brief. Detailed timelines and outcomes will follow source verification.</p></section>
<section className="transition section-pad"><span className="eyebrow">THE OTHER SIDE OF THE PAGE</span><p>That’s the<br/><span>résumé version.</span></p><h2>Here’s the rest<span><Arrow down/></span></h2></section>
<section className="explore section-pad" id="explore"><div className="section-heading"><div><span className="eyebrow">04 / OUTSIDE THE OUTLINE</span><h2>A life, in the margins.</h2></div><p>Places. People. Small things.<br/>An archive taking shape.</p></div><div className="archive-grid">{archive.map((a,i)=><article className={`archive-tile archive-${i}`} key={a.id}><div className="archive-placeholder"><span className="archive-number">0{i+1}</span><div className="archive-art" aria-hidden="true">{i===0?<Arrow/>:i===1?'✳':'◎'}</div><span className="archive-media-note">PHOTOGRAPHY TO COME</span></div><div className="archive-caption"><span className="eyebrow">{a.category}</span><h3>{a.title}</h3></div></article>)}</div><p className="archive-note">The stories are personal. The photographs should be, too.<br/>This space is reserved for my own images and the stories behind them.</p></section>
<section className="contact section-pad" id="contact"><span className="eyebrow">05 / NEXT CONVERSATION</span><h2>Something good<br/>starts with <em>hello.</em></h2><div className="contact-bottom"><p>Product, technology, or a good idea.<br/>Let’s find the overlap.</p><a className="contact-link" href={profile.github} target="_blank" rel="noopener noreferrer">Find me on GitHub <span aria-hidden="true"><Arrow/></span></a></div><p className="small-note">Email and other contact channels will be added after public-sharing approval.</p></section>
</main><footer className="section-pad"><span>© {new Date().getFullYear()} {profile.name}</span><span>BUILT WITH INTENTION. STILL EVOLVING.</span><a href="#home">Back to top ↑</a></footer></>}
